Last minute nav improvements
California-Strawberry-Commission/laser-runner-cutter pull request #29
Opened 2024-08-07 01:08 UTC by DominicChm

Nose to the grindstone :)

2024-08-07 07:54 UTC, genkikondo commented on apps/runner-cutter-app/lib/useGuidanceBrainNode.ts
> +    "~/go_backward",
Wrong service name

2024-08-07 07:56 UTC, genkikondo commented on apps/runner-cutter-app/lib/useGuidanceBrainNode.ts
> +    (_data: any) => undefined, // maps incoming response & solidifies typing info
Can define these input/output mappers in some external functions since they're so common

function triggerInputMapper() {
  return {};
}

function successOutputMapper(res: any): boolean {
  return res.success;
}

2024-08-07 07:57 UTC, genkikondo commented on apps/runner-cutter-app/components/navigation/furrow_preciever_controls.tsx
nit: s/preciever/perceiver in filename

2024-08-07 07:58 UTC, genkikondo commented on apps/runner-cutter-app/lib/useFurrowPerceiverNode.ts
>  const INITIAL_STATE = {
nit: easier to just inline this

2024-08-07 07:59 UTC, genkikondo commented on ros2/furrow_perceiver/furrow_perceiver/furrow_perceiver_node.py
> +    async def emit_state(self):
you probably don't want to await on publishing. I'd use asyncio.create_task(self.state()) instead

2024-08-07 08:07 UTC, genkikondo commented on ros2/runner_cutter_control/launch/web_video_server_launch.py
> -from launch import LaunchDescription
Keep this file and use it in the runner cutter launch file

2024-08-07 08:07 UTC, genkikondo commented on ros2/runner_cutter_control/launch/rosbridge_websocket_launch.xml
> -<!--
Keep this file and use it in the runner cutter launch file

2024-08-07 08:12 UTC, genkikondo commented on ros2/runner_cutter_control/launch/launch.py
> +        package="web_video_server", executable="web_video_server", name="wvs"
add respawn=True, respawn_delay=2.0, just in case

2024-08-07 08:14 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +        return {}
nit: technically result(success=True)

2024-08-07 08:15 UTC, genkikondo commented on ros2/common_interfaces/srv/SetInt32.srv
> +---
nit: add bool success, mainly for consistency with std_srvs

2024-08-07 08:17 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
>          await self.state_topic(self.state)
I don't think we should await publish on topics, as there's no benefit and it slows down callsites. use asyncio.create_task(self.state()) instead

2024-08-29 18:14 UTC, DominicChm commented on ros2/furrow_perceiver/furrow_perceiver/furrow_perceiver_node.py
> +    async def emit_state(self):
Going to address this more concretely in the upcoming refactor.

2024-09-03 10:10 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
>          speed_ms = self.state.speed * 0.00508
What are these magic numbers?

2024-09-03 10:10 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +        # Feed timeout
What does this mean?

2024-09-03 10:10 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +    @subscribe("/furrow1/tracker_result", PositionResult)
Should be perceiver_backward.tracker_result_topic
But assuming from the commented import_node above, it looks like it's still WIP?

2024-09-03 10:10 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +        self.state.speed = self.p.speed
make "p" more descriptive

2024-09-03 10:10 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +    # perceiver_backward = import_node(fpn, "furrow1")
Just checking to make sure this is intended to be commented

2024-09-03 16:19 UTC, DominicChm commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +    # perceiver_backward = import_node(fpn, "furrow1")
It is - result of the bug that prevented nodes from being imported twice. The important topic is explicitly linked below.

2024-09-03 16:54 UTC, DominicChm commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +    @subscribe("/furrow1/tracker_result", PositionResult)
Same as other comment - W/ this version of aioros2 you can't import nodes twice so I was forced to hardcode this path. This is one of the major fixes coming with the next revision.

2024-09-03 17:38 UTC, DominicChm commented on ros2/furrow_perceiver/furrow_perceiver/furrow_perceiver_node.py
> +        await self.state(
Sounds good. I'm planning to provide a "stateful" directive which will automatically publish to a topic whenever a value is written which should help with some of the high frequency messaging. I'll include an option to throttle frequency in that as well.

2024-09-03 17:38 UTC, DominicChm commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +        # Feed timeout
This is a watchdog. Stops movement in case controlling node dies.

2024-09-03 17:38 UTC, DominicChm commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
>          speed_ms = self.state.speed * 0.00508
5000 is completely arbitrary - just maps PID values into a nicer range... Will change that eventually. 0.00508 converts from `ft/min` to `m/s` which the Amiga uses natively.

2024-09-03 17:38 UTC, DominicChm commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +# -12 offset
I'd like to keep for now - these are good default values.

2024-09-03 17:38 UTC, DominicChm commented on ros2/runner_cutter_control/launch/launch.py
> +        emulate_tty=True,
This passes through `print` statements to the console which are normally not shown. There for debugging (hence the spam you mention in the above comment)

2024-09-03 17:38 UTC, DominicChm commented on ros2/runner_cutter_control/launch/launch.py
> +    if importlib.util.find_spec("arena_api"):
I don't install it or cuda in my dev environment b/c the HW isn't there. This just lets me launch. Something to address later.

2024-09-03 17:38 UTC, DominicChm commented on ros2/runner_cutter_control/launch/launch.py
> +    # brain.perceiver_backward.link(furrow_perc1)
This is WIP - will address after refactor (will need to change launch file a bit anyways)

2024-09-03 17:38 UTC, DominicChm commented on ros2/runner_cutter_control/launch/launch.py
> +        package="web_video_server", executable="web_video_server", name="wvs"
IMO something to address later. Good for prod but during testing if a node dies I don't want it to respawn. Let's eventually gate this behind a launch option.

2024-09-03 19:04 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +    # perceiver_backward = import_node(fpn, "furrow1")
ah yup of course. I know you're working on it but TODOs would help for my reference, and to keep track just in case.

2024-09-03 19:06 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +        # Feed timeout
Sounds good. Would you mind expanding the comment to mention that, for future readers?

2024-09-03 19:06 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
>          speed_ms = self.state.speed * 0.00508
Could you add comments?

2024-09-03 20:20 UTC, genkikondo commented on ros2/furrow_perceiver/furrow_perceiver/furrow_perceiver_node.py
> +    async def emit_state(self):
remove `async`

2024-09-03 20:28 UTC, genkikondo approved these changes
No blocking questions, just comments and cleanup at this point so approving

2024-09-18 17:25 UTC, genkikondo requested changes

2024-09-18 17:25 UTC, genkikondo commented on ros2/scripts/run_ros.sh
> +start_lifecycle_manager & start_rosbridge  & start_runner_cutter & start_web_video_server
be sure to revert this change

2024-09-18 17:33 UTC, genkikondo approved these changes

2024-09-18 17:33 UTC, genkikondo commented on ros2/scripts/run_ros.sh
> +start_lifecycle_manager & start_rosbridge  & start_runner_cutter & start_web_video_server
disregard

2024-09-18 17:35 UTC, genkikondo commented on ros2/guidance_brain/guidance_brain/guidance_brain_node.py
> +# -12 offset
shouldn't these be set in params and/or state?

2024-09-18 17:44 UTC, merged